spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=GMT%2B8
    username: zhong
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #没有表新建，有表更新操作,控制台显示建表语句
    show-sql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: false
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
mq:
  exchange: mq.exchange
  ingate:
    queue: mq.ingate.queue








